name: jiitak_ui_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  get: 4.6.6
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
      - family: CustomIcons
        fonts:
          - asset: assets/icons/CustomIcons.ttf
